- name: "AUTOMATED | 4.1.11 | PATCH | Ensure use of privileged commands is collected"
  block:
  - name: "AUTOMATED | 4.1.11 | AUDIT | Ensure use of privileged commands is collected"
    shell: for i in  $(df | grep '^/dev' | awk '{ print $NF }'); do find $i -ignore_readdir_race -xdev -type f -perm -4000 -o -type f -perm -2000; done
    register: priv_procs
    changed_when: no
    check_mode: no

  - name: "AUTOMATED | 4.1.11 | PATCH | Ensure use of privileged commands is collected"
    template:
      src: audit/priv_commands.rules.j2
      dest: /etc/audit/rules.d/priv_commands.rules
      owner: root
      group: root
      mode: 0600
    notify: restart auditd
  when:
  - hs_rhel7cis_rule_4_1_11
  - not rhel7cis_rule_4_1_11
  tags:
  - level2
  - auditd
  - patch
  - automated
  - rule_4.1.11
